### ISSUE TITLE
Make error-msg clear to understand.

### ISSUE THREAD

**Issue by GiG-Roel** [rogerthat-platform/plugin-rogerthat-control-center#161] opened 2017-06-27 13:15 UTC
When changing the title of a sidebar item I was presented with an unclear error.

![screen shot 2017-06-27 at 15 07 40](https://user-images.githubusercontent.com/29431263/27589340-6166cdc6-5b4b-11e7-9eb1-875a27dbe02b.png)

**Comment by lucasvanhalst** [comment] 2017-06-27 13:44
Duplicate of #158.
Will be done when abdelrahman is back.

**Closed by lucasvanhalst** 2017-06-27 13:44 UTC
