### ISSUE TITLE
Bulk update error "200: OK"

### ISSUE THREAD

**Issue by bart-at-mobicage** [rogerthat-platform/plugin-rogerthat-control-center#215] opened 2017-09-20 09:24 UTC
![screen shot 2017-09-20 at 11 24 04](https://user-images.githubusercontent.com/17762105/30636590-3ffa8630-9df6-11e7-9dc0-4760e3918686.png)

**Comment by lucasvanhalst** [comment] 2017-12-08 13:24
Probably duplicate of  #195

**Closed by lucasvanhalst** 2017-12-08 13:24 UTC
Labels: priority_minor, type_bug
